services:
  kotaemon:
    image: mic/kotaemon:latest
    container_name: kotaemon
    volumes:
      - ./ktem_app_data:/app/ktem_app_data
    restart: always
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    ports:
      - "7860:7860"